# Change these first
owner: BBaoVanC # Your GitHub username
repo: status.bbaovanc.com # Your GitHub repository name

# Add your sites here
sites:
  - name: Main Site
    url: https://bbaovanc.com
  - name: Searx
    url: https://searx.bbaovanc.com
  - name: Gitea
    url: https://git.bbaovanc.com
  - name: Images
    url: https://img.bbaovanc.com
  - name: Rick
    url: https://rick.bbaovanc.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.bbaovanc.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: bbaovanc status
  introTitle: "Status of all my websites."
  #introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
